### ISSUE TITLE
Potential type instability with prospective 1.6 type inference changes

### ISSUE THREAD

**Issue by lassepe** [JuliaPOMDP/POMDPModelTools.jl#36]
There is some potential type instability coming our way:
https://github.com/JuliaLang/julia/pull/36208#issuecomment-642226749

This is probably one more reason to register all solvers in the general registry so that all of them are covered by PkgEval reports.

**Comment by JeffBezanson** [comment]
Wow, you did not waste any time noticing this! :) But stay tuned, I might have a mitigation in Base for this.

**Comment by zsunberg** [comment]
Haha wow @lassepe , how did you even notice this? It looks like the error is in the info section which will be made better when POMDPs.jl 0.9 is released, so I wouldn't worry about it too much. As long as POMDPs is passing, I think it will probably be fixed in the future.

That being said, @lassepe you are probably right that we should register the solvers because they might be a pretty good test of the inference engine.

**Comment by lassepe** [comment]
@zsunberg I was reading stuff in Base and saw this pop up. But this should actually not be an issue anymore as of https://github.com/JuliaLang/julia/pull/36208/commits/73df43ab77cdadbe5080d90ab852c42d16678089. Thank you @JeffBezanson !
